#!/usr/bin/env python3
"""Where an article's split PDF actually is.

toc.json records ``split_pdf`` relative to the repository root that generated
it. That was itself a fix -- absolute paths are how 36.1 got hollowed out on
2026-08-03, generated on one host and resolving on no other -- but it ties the
folder to one repo, and since 2026-08-18 there are two.

The content pipeline now lives in Harbour (``scripts/pipeline/``), and both
repos read the SAME output directory. A folder Harbour generated records
``./scripts/pipeline/private/output/...``; run pipe6 over it from here and
``os.path.exists`` is False for every article, so the import XML comes out with
no PDF galleys and says nothing. That is what this module exists to stop.

The split PDF is always a sibling of the toc.json that describes it, so that is
what we resolve against; the stored path is used only for its filename. This is
a copy of ``scripts/pipeline/lib/paths.py`` in the Harbour repo -- deliberately,
because the two repos share no code and this file is fifteen lines.
"""

import os


def article_pdf(toc_path, article):
    """Absolute path to an article's split PDF, or None if it has none.

    Returns the path whether or not the file exists -- callers that treat a
    missing PDF as a skip need to say so themselves.
    """
    stored = (article or {}).get('split_pdf') or ''
    if not stored:
        return None

    vol_dir = os.path.dirname(os.path.abspath(toc_path))
    sibling = os.path.join(vol_dir, os.path.basename(stored))
    if os.path.exists(sibling):
        return sibling

    # Fall back to the stored path, so a toc.json that deliberately points
    # outside its own folder keeps working.
    literal = stored[2:] if stored.startswith('./') else stored
    return os.path.abspath(literal)


def load_toc(toc_path):
    """Load a toc.json with every ``split_pdf`` resolved against the folder.

    Normalising once here, rather than at each of the dozen places that derive
    a .jats.xml or .galley.html from ``split_pdf``, is what lets the OJS
    delivery stages consume a folder generated by either pipeline. None of them
    writes toc.json back, so replacing the stored value in memory cannot persist
    an absolute path -- which is the failure this file's header warns about.
    """
    import json

    with open(toc_path) as f:
        toc = json.load(f)

    for article in toc.get('articles', []):
        resolved = article_pdf(toc_path, article)
        if resolved:
            article['split_pdf'] = resolved

    return toc
