"""The OJS delivery stages must accept a folder generated by either pipeline.

Since 2026-08-18 the content pipeline lives in Harbour (`scripts/pipeline/`) and
both repos read the same output directory. toc.json records `split_pdf` relative
to the repository root that generated it, so a Harbour-generated folder records
`./scripts/pipeline/private/output/...`, which resolves to nothing from here.

Before lib/paths.py, pipe6 refused the whole issue: "22 of 22 articles have no
galleys". Loud, but a blocked run. HARBOUR_SHAPE below is the literal string
Harbour's split2_split_pdf writes, and OLD_SHAPE is what is in every toc.json in
private/backfill/output today.
"""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from lib.paths import article_pdf, load_toc

OLD_SHAPE = './backfill/private/output/37.2/01-editorial.pdf'
HARBOUR_SHAPE = './scripts/pipeline/private/output/37.2/01-editorial.pdf'


def _issue(tmp_path, stored):
    import json
    d = tmp_path / '37.2'
    d.mkdir(parents=True)
    (d / '01-editorial.pdf').write_bytes(b'%PDF-1.4\n')
    (d / '01-editorial.jats.xml').write_text('<article/>')
    toc = d / 'toc.json'
    toc.write_text(json.dumps({'volume': 37, 'issue': 2,
                               'articles': [{'title': 'Editorial', 'split_pdf': stored}]}))
    return toc, d


def test_a_folder_from_either_pipeline_resolves_the_same(tmp_path):
    for name, stored in (('old', OLD_SHAPE), ('harbour', HARBOUR_SHAPE)):
        toc, d = _issue(tmp_path / name, stored)
        found = article_pdf(toc, {'split_pdf': stored})
        assert found == str(d / '01-editorial.pdf'), name
        assert os.path.exists(found), name


def test_load_toc_rewrites_every_article(tmp_path):
    toc, d = _issue(tmp_path, HARBOUR_SHAPE)

    loaded = load_toc(toc)

    stored = loaded['articles'][0]['split_pdf']
    assert stored == str(d / '01-editorial.pdf')
    # The sibling derivations every stage does off split_pdf now land.
    assert os.path.exists(os.path.splitext(stored)[0] + '.jats.xml')


def test_load_toc_leaves_an_article_without_a_pdf_alone(tmp_path):
    import json
    d = tmp_path / '37.2'
    d.mkdir()
    toc = d / 'toc.json'
    toc.write_text(json.dumps({'articles': [{'title': 'No PDF'}]}))

    assert load_toc(toc)['articles'][0].get('split_pdf') is None


def test_every_ojs_stage_loads_through_it():
    """A stage that goes back to a bare json.load reintroduces the break."""
    import re
    here = os.path.dirname(os.path.abspath(__file__))
    stages = ['pipe6_ojs_xml.py', 'pipe8_restore.py', 'pipe10_verify.py',
              'pipe9b_citation_dois.py', 'pipe9c_content_filtered.py',
              'pipe13_patch_metadata.py']
    for name in stages:
        src = open(os.path.join(here, '..', 'html_pipeline', name), encoding='utf-8').read()
        assert 'load_toc' in src, f'{name} does not use load_toc'
        # No stage may load a toc.json directly any more.
        assert not re.search(r'json\.load\(open\(toc_path', src), name
